AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0fb08b4ce57852c53
      InstanceType: t2.micro
      KeyName: HS1
      